# Generated by Django 5.2.17 on 2026-08-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('opening_hours', models.JSONField(blank=True, default=dict, help_text='e.g. {"mon": ["09:00", "21:00"], "sun": null}')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_demo_data', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='The pharmacy-role user account that manages this pharmacy.', limit_choices_to={'role': 'pharmacy'}, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pharmacies',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='pharmacies__latitud_79a150_idx'), models.Index(fields=['verification_status'], name='pharmacies__verific_56726e_idx')],
            },
        ),
    ]
