# Generated by Django 5.2.17 on 2026-08-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matching_basis', models.CharField(choices=[('composition', 'Composition'), ('strength', 'Strength'), ('dosage_form', 'Dosage Form'), ('therapeutic_category', 'Therapeutic Category'), ('combined', 'Combined Attributes')], max_length=30)),
                ('confidence_score', models.FloatField(help_text='0.0–1.0 attribute-similarity score, not a clinical rating.')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_candidate_of', to='medicines.medicine')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative_candidates_for', to='medicines.medicine')),
                ('verified_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_alternatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-confidence_score'],
                'indexes': [models.Index(fields=['medicine', 'verification_status'], name='alternative_medicin_295666_idx')],
                'constraints': [models.UniqueConstraint(fields=('medicine', 'candidate_medicine'), name='unique_medicine_candidate_pair'), models.CheckConstraint(condition=models.Q(('medicine', models.F('candidate_medicine')), _negated=True), name='candidate_must_differ_from_medicine')],
            },
        ),
    ]
