# Generated by Django 5.2.17 on 2026-08-23 10:40

import django.db.models.deletion
import prescriptions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_file', models.FileField(upload_to=prescriptions.models.prescription_upload_path)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw OCR output. Never included in application logs.')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(max_length=255)),
                ('extracted_strength', models.CharField(blank=True, max_length=50)),
                ('match_confidence', models.FloatField(default=0.0, help_text='0.0–1.0 fuzzy-match confidence to `medicine`.')),
                ('user_confirmed', models.BooleanField(default=False)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_mentions', to='medicines.medicine')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_medicines', to='prescriptions.prescription')),
            ],
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['user', 'created_at'], name='prescriptio_user_id_92aecf_idx'),
        ),
        migrations.AddIndex(
            model_name='prescriptionmedicine',
            index=models.Index(fields=['prescription'], name='prescriptio_prescri_823f90_idx'),
        ),
    ]
