# Generated by Django 5.2.17 on 2026-08-27 15:40

import prescriptions.models
import prescriptions.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='uploaded_file',
            field=models.FileField(storage=prescriptions.storage.PrivatePrescriptionStorage(), upload_to=prescriptions.models.prescription_upload_path),
        ),
    ]
