# Generated by Django 5.2.17 on 2026-08-23 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(db_index=True, max_length=200)),
                ('composition', models.CharField(help_text="Active ingredient(s), e.g. 'Paracetamol' or 'Amoxicillin + Clavulanic Acid'.", max_length=300)),
                ('strength', models.CharField(help_text="e.g. '650mg', '500mg/5ml'", max_length=50)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream/Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('other', 'Other')], default='tablet', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('therapeutic_category', models.CharField(blank=True, db_index=True, max_length=150)),
                ('prescription_required', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('normalized_search_key', models.CharField(blank=True, db_index=True, editable=False, max_length=500)),
                ('is_demo_data', models.BooleanField(default=False, help_text='True if seeded by the demo data generator rather than a real import.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['brand_name'], name='medicines_m_brand_n_d788ba_idx'), models.Index(fields=['generic_name'], name='medicines_m_generic_1e9386_idx'), models.Index(fields=['therapeutic_category'], name='medicines_m_therape_a47bda_idx')],
                'constraints': [models.UniqueConstraint(fields=('brand_name', 'strength', 'manufacturer'), name='unique_medicine_brand_strength_manufacturer')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(help_text='Raw text the user typed.', max_length=200)),
                ('location_text', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_events', to='medicines.medicine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['medicine', 'timestamp'], name='medicines_s_medicin_5742d2_idx'), models.Index(fields=['user', 'timestamp'], name='medicines_s_user_id_8a626f_idx')],
            },
        ),
    ]
